import curses

EMPTY = "  "
WHITE_DISC = "🔴"  # "⚪"
BLACK_DISC = "🔵"  # "⚫"
VALID_MOVE_MARK = "・"

WHITE_CURSOR_FG = curses.COLOR_RED
WHITE_CURSOR_BG = curses.COLOR_RED
BLACK_CURSOR_FG = curses.COLOR_BLUE
BLACK_CURSOR_BG = curses.COLOR_BLUE

VERTICAL_LINE = "┃"
HORIZONTAL_LINE = "━━"
TOP_LEFT_EDGE_LINE = "┏"
TOP_RIGHT_EDGE_LINE = "┓"
BOTTOM_LEFT_EDGE_LINE = "┗"
BOTTOM_RIGHT_EDGE_LINE = "┛"
